In [1]:
from service_connector import ServiceConnector
import asyncio
import nest_asyncio
nest_asyncio.apply()


service_connector = ServiceConnector()
loop = asyncio.get_event_loop()

In [2]:
# Запрос данных о 4000 репозиторев за 4 месяца, которые имеют минимум 100 звезд
github_data = loop.run_until_complete(service_connector.get_data("2024-01-01", "2024-04-01", 1000, 200))
github_data

,repo,pushes,avg_push_size,pull_requests,merged_pull_requests_ratio,issues,closed_issues_ratio,watches,forks,language,license_name,is_deleted_or_private
0,ame-fire/Sakurai-Project,1,1.0,0,0.0,0,0.0,289,0,None,None,True
1,Jonatas45124/Trading-View-2024-Crack-main,2,1.0,0,0.0,0,0.0,211,0,None,None,True
2,dtony598/dtony5981,2,1.0,0,0.0,0,0.0,207,0,None,None,True
3,AIGCDesignGroup/ReplaceAnything,25,1.0,1,0.0,13,0.0,1999,77,None,None,False
4,Hanajis/Hanajis1,2,1.0,0,0.0,0,0.0,263,0,None,None,True
...,...,...,...,...,...,...,...,...,...,...,...,...
573,krisM7723/View,3,1.0,0,0.0,0,0.0,204,0,None,None,True
574,Sh3lldon/FullBypass,27,1.0,0,0.0,0,0.0,389,74,C#,GNU General Public License v3.0,False
574,Sh3lldon/FullBypass,27,1.0,0,0.0,0,0.0,389,74,C#,GNU General Public License v3.0,False
575,pi0/config-dir,9,1.0,1,0.0,5,0.2,211,1,None,None,False
576,AINativeLab/gptstore-data-backup,51,1.0,2,0.0,2,0.5,202,8,None,None,False

In [6]:
# Пример таблицы с децилями по выборке (Не этих данных)
find_quantile_columns(github_data, 'deciles')

,pushes,avg_push_size,pull_requests,merged_pull_requests_ratio,issues,closed_issues_ratio,watches,forks
0.1,0.0,0.000000,0.0,0.0,0.0,0.000000,10.0,0.0
0.2,0.0,0.000000,0.0,0.0,0.0,0.000000,12.0,0.0
0.3,1.0,1.000000,0.0,0.0,0.0,0.000000,13.4,0.0
0.4,1.0,1.000000,0.0,0.0,0.0,0.000000,16.0,0.0
0.5,2.0,1.000000,0.0,0.0,0.0,0.000000,19.0,0.0
0.6,3.0,1.000000,0.0,0.0,0.0,0.000000,23.0,0.0
0.7,7.0,1.000000,0.0,0.0,0.0,0.000000,29.0,1.0
0.8,14.0,1.019043,0.0,0.0,1.0,0.000000,48.4,2.4
0.9,33.2,1.294754,2.0,0.0,3.0,0.333333,118.6,6.0

In [3]:
from github_data_converter import GithubDataConverter
from pattern_miner import PatternMiner


# Конвертирование в транзакции
github_data_converter = GithubDataConverter()
transactions = github_data_converter.convert_data_to_transactions(github_data, 'deciles')
transactions

d:\WorkData\SusuRepos\final-qualifying-work\project\github_data_converter.py:141: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data.drop('repo', axis=1, inplace=True)

,isdeleted or private,pushes 1,pushes 10,pushes 2,pushes 3,pushes 35,pushes 4,avg push size 1.0,avg push size 1.27,pull requests 0,...,Creative Commons Zero v1.0 Universal,GNU Affero General Public License v3.0,GNU General Public License v2.0,GNU General Public License v3.0,MIT License,Mozilla Public License 2.0,None,Other,SIL Open Font License 1.1,The Unlicense
0,True,True,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
1,True,False,False,True,False,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
2,True,False,False,True,False,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
4,True,False,False,True,False,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,False,False,False,True,False,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
572,True,True,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
573,True,False,False,False,True,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
575,False,False,True,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
576,False,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False

In [4]:
# Поиск шаблонов
pattern_miner = PatternMiner()
patterns = pattern_miner.mine_patterns(transactions, 0.1, 0.1, 1)
patterns

,antecedents,consequents,support,confidence,lift
0,(pushes 1),(isdeleted or private),0.3035,0.8384,1.3370
1,(isdeleted or private),(pushes 1),0.3035,0.4840,1.3370
2,(isdeleted or private),(pushes 2),0.1846,0.2945,1.2683
3,(pushes 2),(isdeleted or private),0.1846,0.7953,1.2683
4,(avg push size 1.0),(isdeleted or private),0.6216,0.7158,1.1415
...,...,...,...,...,...
4315,"(issues 0), (None), (forks 0)",(watches 213),0.1225,0.2000,1.2292
4326,"(watches 213), (None), (forks 0)",(closed issues ratio 0.0),0.1225,1.0000,1.2604
4327,"(watches 213), (None), (closed issues ratio 0.0)",(forks 0),0.1225,0.9853,1.4258
4328,"(watches 213), (forks 0), (closed issues ratio...",(None),0.1225,0.9306,1.3502
4329,"(None), (forks 0), (closed issues ratio 0.0)",(watches 213),0.1225,0.2000,1.2292

In [13]:
# Сохранение в excel
patterns.to_excel("data/patterns.xlsx")