In [9]:
from service_connector import ServiceConnector
import asyncio
import nest_asyncio
nest_asyncio.apply()


service_connector = ServiceConnector()
loop = asyncio.get_event_loop()

In [10]:
# Запрос данных о 4000 репозиторев за 4 месяца, которые имеют минимум 100 звезд
github_data = loop.run_until_complete(service_connector.get_data("2024-01-01", "2024-04-01", 4000, 100))
github_data

,repo,pushes,avg_push_size,pull_requests,merged_pull_requests_ratio,issues,closed_issues_ratio,watches,forks,language,license_name,is_deleted_or_private
0,babangucok/babangucok1,1,1.000000,0,0.0,0,0.0,232,0,None,None,True
1,ElFo2K/m0d,2,1.000000,0,0.0,0,0.0,166,0,None,None,True
2,MehzoozNizar/Rust-Hack,5,1.000000,0,0.0,0,0.0,471,0,None,None,True
3,Jonatas45124/Trading-View-Crack-main,2,1.000000,0,0.0,0,0.0,226,0,None,None,True
4,ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM,11,1.090909,0,0.0,10,0.1,105,10,Python,GNU General Public License v3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1273,lucascottet/ITOP-SCREEN-RECORDER-CRACK,1,1.000000,0,0.0,0,0.0,136,0,None,None,True
1274,cognitivecomputations/laserRMT,13,2.076923,16,0.0,10,0.4,141,19,Python,Apache License 2.0,False
1275,Enndfp/short-link,19,2.368421,0,0.0,0,0.0,110,2,Java,MIT License,False
1275,Enndfp/short-link,19,2.368421,0,0.0,0,0.0,110,2,Java,MIT License,False
1276,Bastami229/TW,1,1.000000,0,0.0,0,0.0,315,0,None,None,True

In [6]:
# Пример таблицы с децилями по выборке (Не этих данных)
find_quantile_columns(github_data, 'deciles')

,pushes,avg_push_size,pull_requests,merged_pull_requests_ratio,issues,closed_issues_ratio,watches,forks
0.1,0.0,0.000000,0.0,0.0,0.0,0.000000,10.0,0.0
0.2,0.0,0.000000,0.0,0.0,0.0,0.000000,12.0,0.0
0.3,1.0,1.000000,0.0,0.0,0.0,0.000000,13.4,0.0
0.4,1.0,1.000000,0.0,0.0,0.0,0.000000,16.0,0.0
0.5,2.0,1.000000,0.0,0.0,0.0,0.000000,19.0,0.0
0.6,3.0,1.000000,0.0,0.0,0.0,0.000000,23.0,0.0
0.7,7.0,1.000000,0.0,0.0,0.0,0.000000,29.0,1.0
0.8,14.0,1.019043,0.0,0.0,1.0,0.000000,48.4,2.4
0.9,33.2,1.294754,2.0,0.0,3.0,0.333333,118.6,6.0

In [11]:
from github_data_converter import GithubDataConverter
from pattern_miner import PatternMiner


# Конвертирование в транзакции
github_data_converter = GithubDataConverter()
transactions = github_data_converter.convert_data_to_transactions(github_data, 'deciles')
transactions

d:\WorkData\SusuRepos\final-qualifying-work\project\github_data_converter.py:141: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data.drop('repo', axis=1, inplace=True)

,Удален или скрыт,pushes 1,pushes 11,pushes 2,pushes 3,pushes 33,pushes 5,avg push size 1.0,avg push size 1.25,pull requests 0,...,GNU Affero General Public License v3.0,GNU General Public License v2.0,GNU General Public License v3.0,MIT License,Mozilla Public License 2.0,None,Other,SIL Open Font License 1.1,The Unlicense,zlib License
0,True,True,False,False,False,False,False,True,False,True,...,False,False,False,False,False,True,False,False,False,False
1,True,False,False,True,False,False,False,True,False,True,...,False,False,False,False,False,True,False,False,False,False
2,True,False,False,False,False,False,True,True,False,True,...,False,False,False,False,False,True,False,False,False,False
3,True,False,False,True,False,False,False,True,False,True,...,False,False,False,False,False,True,False,False,False,False
4,False,False,True,False,False,False,False,True,False,True,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,True,False,True,False,False,False,False,True,False,True,...,False,False,False,False,False,True,False,False,False,False
1272,True,False,False,True,False,False,False,True,False,True,...,False,False,False,False,False,True,False,False,False,False
1273,True,True,False,False,False,False,False,True,False,True,...,False,False,False,False,False,True,False,False,False,False
1274,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1276,True,True,False,False,False,False,False,True,False,True,...,False,False,False,False,False,True,False,False,False,False

In [12]:
# Поиск шаблонов
pattern_miner = PatternMiner()
patterns = pattern_miner.mine_patterns(transactions, 0.1, 0.1, 1)
patterns

,antecedents,consequents,support,confidence,lift
0,(pushes 1),(Удален или скрыт),0.3279,0.8085,1.4065
1,(Удален или скрыт),(pushes 1),0.3279,0.5704,1.4065
2,(pushes 2),(Удален или скрыт),0.1406,0.7818,1.3601
3,(Удален или скрыт),(pushes 2),0.1406,0.2447,1.3601
4,(avg push size 1.0),(Удален или скрыт),0.5724,0.6542,1.1381
...,...,...,...,...,...
3655,"(watches 112), (issues 0), (closed issues rati...",(None),0.1047,0.8707,1.3848
3666,"(forks 0), (None), (issues 0)",(closed issues ratio 0.0),0.5658,1.0000,1.2014
3667,"(forks 0), (None), (closed issues ratio 0.0)",(issues 0),0.5658,1.0000,1.2556
3668,"(forks 0), (issues 0), (closed issues ratio 0.0)",(None),0.5658,0.8327,1.3244
3669,"(None), (issues 0), (closed issues ratio 0.0)",(forks 0),0.5658,0.9301,1.3590

In [13]:
# Сохранение в excel
patterns.to_excel("data/patterns.xlsx")