In [1]:
from service_connector import ServiceConnector
import asyncio
import nest_asyncio
nest_asyncio.apply()


service_connector = ServiceConnector()
loop = asyncio.get_event_loop()

# Запрос данных о 4000 репозиторев за 4 месяца, которые имеют минимум 100 звезд
transactions_dict = {'pushes': 'dec',
                    'avg_push_size': 'dec',
                    'pull_requests': 'qua',
                    'merged_pull_requests_ratio': 'dec',
                    'issues': 'dec',
                    'closed_issues_ratio': 'qua',
                    'watches': 'dec',
                    'forks': 'dec',
                    'new_members': 'dec',
                    'language': 'None',
                    'license_name': 'None',
                    'is_deleted_or_private': 'None'}

github_data = loop.run_until_complete(service_connector.get_data_from_services(
                                                                 transactions_dict,
                                                                 "2023-01-01", 
                                                                 "2023-08-01", 
                                                                 limit=500,
                                                                #  min_watch_event_count=200,
                                                                #  min_new_members_count=3,
                                                                 is_new_repos=False))
github_data

,repo,pushes,avg_push_size,pull_requests,merged_pull_requests_ratio,issues,closed_issues_ratio,watches,forks,new_members,language,license_name,is_deleted_or_private
0,julycoding/ChatGPT_principle_fine-tuning_code_...,83,1.30,19,0.37,0,0.00,77,23,6,None,None,False
1,Endava/bee-q,784,5.62,731,0.32,3,0.33,21,10,5,TypeScript,Apache License 2.0,False
2,shiX0/Medwell,140,13.31,112,0.48,0,0.00,25,1,3,Dart,MIT License,False
3,alibaba/MNN,48,2.94,90,0.33,871,0.68,572,117,3,C++,None,False
4,grommet/grommet,388,1.58,342,0.44,265,0.40,188,45,3,JavaScript,Apache License 2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,hr07exploiter/PentiumOps-Network-Sniffer-Monit...,26,1.00,0,0.00,0,0.00,17,0,4,Python,None,False
495,iterative/dvclive,340,2.00,255,0.40,162,0.50,33,14,9,Python,Apache License 2.0,False
496,IIC2613-Inteligencia-Artificial-2023-1/Syllabus,18,1.00,0,0.00,165,0.45,44,0,10,Jupyter Notebook,None,False
497,google/fhir-data-pipes,547,2.26,382,0.24,151,0.35,42,19,13,Java,Apache License 2.0,False
498,zjunlp/DeepKE,434,1.31,16,0.44,176,0.51,600,144,3,Python,MIT License,False

In [2]:
from github_data_converter import GithubDataConverter
from pattern_miner import PatternMiner


# Конвертирование в транзакции
github_data_converter = GithubDataConverter()
transactions = github_data_converter.convert_data_to_transactions(github_data,                                                         
        {'pushes': 'qua',
        'avg_push_size': 'qua',
        'pull_requests': 'qua',
        'merged_pull_requests_ratio': 'qua',
        'issues': 'qua',
        'closed_issues_ratio': 'qua',
        'watches': 'qua',
        'forks': 'qua',
        'new_members': 'qua'})
transactions

,isdeleted or private,pushes 152.0,pushes 41.5,pushes 459.0,avg push size 1.295,avg push size 2.08,avg push size 3.5949999999999998,pull requests 16.0,pull requests 311.5,pull requests 90.0,...,Creative Commons Zero v1.0 Universal,European Union Public License 1.2,GNU Affero General Public License v3.0,GNU General Public License v2.0,GNU General Public License v3.0,GNU Lesser General Public License v2.1,GNU Lesser General Public License v3.0,MIT License,Mozilla Public License 2.0,PostgreSQL License
0,False,False,True,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,False,False,True,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,True,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,False,False,True,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
495,False,False,False,True,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
496,False,False,True,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
497,False,False,False,True,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
498,False,False,False,True,True,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [4]:
# Поиск шаблонов
pattern_miner = PatternMiner()
patterns = pattern_miner.mine_patterns(transactions, 0.1, 0.1, 1)
patterns

,antecedents,consequents,support,confidence,lift
0,(pushes 1197.1999999999998),(pull requests 304.5),0.1162,0.9063,2.6918
1,(pull requests 304.5),(pushes 1197.1999999999998),0.1162,0.3452,2.6918
2,(pushes 13.0),(pull requests 13.5),0.1383,0.9452,2.4312
3,(pull requests 13.5),(pushes 13.0),0.1383,0.3557,2.4312
4,(pushes 594.6000000000005),(pull requests 304.5),0.1002,0.7937,2.3573
5,(pull requests 304.5),(pushes 594.6000000000005),0.1002,0.2976,2.3573
6,(pull requests 13.5),(avg push size 1.04),0.1222,0.3144,2.0116
7,(avg push size 1.04),(pull requests 13.5),0.1222,0.7821,2.0116
8,(pull requests 13.5),(merged pull requests ratio 0.0),0.1383,0.3557,2.3049
9,(merged pull requests ratio 0.0),(pull requests 13.5),0.1383,0.8961,2.3049
10,(issues 0.0),(pull requests 13.5),0.1263,0.6848,1.7614
11,(pull requests 13.5),(issues 0.0),0.1263,0.3247,1.7614
12,(closed issues ratio 0.0),(pull requests 13.5),0.1984,0.6429,1.6535
13,(pull requests 13.5),(closed issues ratio 0.0),0.1984,0.5103,1.6535
14,(pull requests 13.5),(forks 1.0),0.1343,0.3454,1.7408
15,(forks 1.0),(pull requests 13.5),0.1343,0.6768,1.7408
16,(new members 3.0),(pull requests 13.5),0.1884,0.4796,1.2336
17,(pull requests 13.5),(new members 3.0),0.1884,0.4845,1.2336
18,(pull requests 13.5),(MIT License),0.1222,0.3144,1.1207
19,(MIT License),(pull requests 13.5),0.1222,0.4357,1.1207
20,(pull requests 304.5),(issues 362.2),0.1162,0.3452,2.5334
21,(issues 362.2),(pull requests 304.5),0.1162,0.8529,2.5334
22,(pull requests 304.5),(closed issues ratio 0.4),0.1102,0.3274,1.0274
23,(closed issues ratio 0.4),(pull requests 304.5),0.1102,0.3459,1.0274
24,(closed issues ratio 0.48),(pull requests 304.5),0.1804,0.4839,1.4372
25,(pull requests 304.5),(closed issues ratio 0.48),0.1804,0.5357,1.4372
26,(pull requests 304.5),(forks 115.79999999999995),0.1002,0.2976,2.2166
27,(forks 115.79999999999995),(pull requests 304.5),0.1002,0.7463,2.2166
28,(Apache License 2.0),(pull requests 304.5),0.1162,0.4640,1.3782
29,(pull requests 304.5),(Apache License 2.0),0.1162,0.3452,1.3782
30,(pull requests 80.0),(closed issues ratio 0.4),0.1062,0.3869,1.2141
31,(closed issues ratio 0.4),(pull requests 80.0),0.1062,0.3333,1.2141
32,(pull requests 80.0),(closed issues ratio 0.48),0.1042,0.3796,1.0183
33,(closed issues ratio 0.48),(pull requests 80.0),0.1042,0.2796,1.0183
34,(closed issues ratio 0.0),(issues 0.0),0.1844,0.5974,3.2403
35,(issues 0.0),(closed issues ratio 0.0),0.1844,1.0000,3.2403
36,(closed issues ratio 0.0),(forks 1.0),0.1102,0.3571,1.8001
37,(forks 1.0),(closed issues ratio 0.0),0.1102,0.5556,1.8001
38,(new members 3.0),(closed issues ratio 0.4),0.1303,0.3316,1.0408
39,(closed issues ratio 0.4),(new members 3.0),0.1303,0.4088,1.0408
40,(new members 3.0),(closed issues ratio 0.48),0.1503,0.3827,1.0266
41,(closed issues ratio 0.48),(new members 3.0),0.1503,0.4032,1.0266
42,(closed issues ratio 0.48),(Apache License 2.0),0.1162,0.3118,1.2448
43,(Apache License 2.0),(closed issues ratio 0.48),0.1162,0.4640,1.2448
44,(closed issues ratio 0.48),(MIT License),0.1142,0.3065,1.0923
45,(MIT License),(closed issues ratio 0.48),0.1142,0.4071,1.0923
46,(new members 3.0),(Apache License 2.0),0.1102,0.2806,1.1202
47,(Apache License 2.0),(new members 3.0),0.1102,0.4400,1.1202
48,(new members 3.0),(MIT License),0.1242,0.3163,1.1275
49,(MIT License),(new members 3.0),0.1242,0.4429,1.1275
50,"(closed issues ratio 0.0), (issues 0.0)",(pull requests 13.5),0.1263,0.6848,1.7614
51,"(closed issues ratio 0.0), (pull requests 13.5)",(issues 0.0),0.1263,0.6364,3.4516
52,"(issues 0.0), (pull requests 13.5)",(closed issues ratio 0.0),0.1263,1.0000,3.2403

In [ ]:
# Сохранение в excel
patterns.to_excel("data/patterns.xlsx")