In [1]:
from service_connector import ServiceConnector
import asyncio
import nest_asyncio
nest_asyncio.apply()


service_connector = ServiceConnector()
loop = asyncio.get_event_loop()

# Запрос данных о 4000 репозиторев за 4 месяца, которые имеют минимум 100 звезд
transactions_dict = ['pushes'
                    'avg_push_size',
                    'pull_requests',
                    'merged_pull_requests_ratio',
                    'issues',
                    'closed_issues_ratio',
                    'watches',
                    'forks',
                    'new_members',
                    'language',
                    'license_name',
                    'is_deleted_or_private']

github_data = loop.run_until_complete(service_connector.get_data_from_services(
                                                                 transactions_dict,
                                                                 "2023-01-01", 
                                                                 "2023-06-01", 
                                                                 limit=1000,
                                                                 min_watch_event_count=100,
                                                                 min_new_members_count=2,
                                                                 is_new_repos=False))
github_data

ImportError: attempted relative import with no known parent package

In [3]:
from github_data_converter import GithubDataConverter
from pattern_miner import PatternMiner


# Конвертирование в транзакции
github_data_converter = GithubDataConverter()
transactions = github_data_converter.convert_data_to_transactions(github_data,                                                         
        {'pushes': 'dec',
        'avg_push_size': 'qua',
        'pull_requests': 'dec',
        'merged_pull_requests_ratio': 'dec',
        'issues': 'dec',
        'closed_issues_ratio': 'dec',
        'watches': 'dec',
        'forks': 'dec',
        'new_members': 'dec'})
transactions

,isdeleted or private,pushes 1,pushes 10,pushes 2,pushes 3,pushes 4,pushes 5,pushes 6,pushes 7,pushes 8,...,GNU General Public License v3.0,GNU Lesser General Public License v2.1,GNU Lesser General Public License v3.0,ISC License,MIT License,Mozilla Public License 2.0,Open Software License 3.0,PostgreSQL License,The Unlicense,Universal Permissive License v1.0
0,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
995,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
997,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False

In [8]:
# Поиск шаблонов
pattern_miner = PatternMiner()
patterns = pattern_miner.mine_patterns(transactions, 0.01, 0.1, 1)
patterns

,antecedents,consequents,support,confidence,lift
0,(pushes 1),(avg push size 1),0.0621,0.6200,2.4676
1,(avg push size 1),(pushes 1),0.0621,0.2470,2.4676
2,(pushes 1),(avg push size 2),0.0270,0.2700,1.0789
3,(avg push size 2),(pushes 1),0.0270,0.1080,1.0789
4,(pushes 1),(pull requests 1),0.0601,0.6000,5.9940
...,...,...,...,...,...
11776,"(forks 1), (MIT License), (new members 6)",(watches 1),0.0100,0.7143,7.1357
11784,"(watches 1), (forks 1), (Apache License 2.0)",(Python),0.0110,0.5789,2.4823
11785,"(watches 1), (forks 1), (Python)",(Apache License 2.0),0.0110,0.4074,1.3045
11786,"(watches 1), (Apache License 2.0), (Python)",(forks 1),0.0110,0.6471,6.4641
11787,"(forks 1), (Apache License 2.0), (Python)",(watches 1),0.0110,0.7857,7.8493

In [7]:
# Сохранение в excel
patterns.to_excel("patterns.xlsx")